export const DISPLAY_INDICATORS = 'DISPLAY_INDICATORS';
export const DISPLAY_ESTIMATES = 'DISPLAY_ESTIMATES';
export const DISPLAY_FEATURES = 'DISPLAY_FEATURES';
export const DISPLAY_VERSIONS = 'DISPLAY_VERSIONS';
export const DISPLAY_REPORTERS = 'DISPLAY_REPORTERS';

export const CHANGE_VISIBILITY_SPRINT_TIMELINE = 'CHANGE_VISIBILITY_SPRINT_TIMELINE';
export const CHANGE_VISIBILITY_TASK_STATUS = 'CHANGE_VISIBILITY_TASK_STATUS';
export const CHANGE_VISIBILITY_ISSUES = 'CHANGE_VISIBILITY_ISSUES';
export const CHANGE_VISIBILITY_BURNDOWN = 'CHANGE_VISIBILITY_BURNDOWN';
