export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const SEARCH_TEXT_CHANGED = "SEARCH_TEXT_CHANGED";
export const SET_COLLAPSING_SUBTASKS = "SET_COLLAPSING_SUBTASKS";
export const SET_COLLAPSING_BUGS = "SET_COLLAPSING_BUGS";
export const FILTER_STARRED_ISSUES = "FILTER_STARRED_ISSUES";

export const ADD_TASK_STATUS_FILTERS = "ADD_TASK_STATUS_FILTERS";
export const REMOVE_TASK_STATUS_FILTERS = "REMOVE_TASK_STATUS_FILTERS";
