export const RECENTLY_UPDATED_REFRESH = "RECENTLY_UPDATED_REFRESH";
export const RECENTLY_UPDATED_STARTED = "RECENTLY_UPDATED_STARTED";
export const RECENTLY_UPDATED_FINISHED = "RECENTLY_UPDATED_FINISHED";

export const GET_PREFERENCES = "GET_PREFERENCES";
export const GET_SPRINT_ISSUES = "GET_SPRINT_ISSUES";

export const RELOAD_ISSUES = "RELOAD_ISSUES";
export const REFRESH_ISSUES = "REFRESH_ISSUES";
export const REFRESH_GANTT = "REFRESH_GANTT";
export const REFRESH_GANTT_STARTED = "REFRESH_GANTT_STARTED";
export const REFRESH_GANTT_FINISHED = "REFRESH_GANTT_FINISHED";

export const SET_SPRINT_SUMMARY = "SET_SPRINT_SUMMARY";
export const SET_SPRINT_DATES = "SET_SPRINT_DATES";
export const SET_SPRINT_ISSUES = "SET_SPRINT_ISSUES";
export const SET_SPRINT_VELOCITY = "SET_SPRINT_VELOCITY";

export const SET_ISSUES_SUMMARIES = "SET_ISSUES_SUMMARIES";
