export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const DISPLAY_INDICATORS = 'DISPLAY_INDICATORS';
export const DISPLAY_ESTIMATES = 'DISPLAY_ESTIMATES';
export const DISPLAY_FEATURES = 'DISPLAY_FEATURES';
export const DISPLAY_VERSIONS = 'DISPLAY_VERSIONS';
export const DISPLAY_REPORTERS = 'DISPLAY_REPORTERS';

export const RECENTLY_UPDATED_REFRESH = "RECENTLY_UPDATED_REFRESH";
export const RECENTLY_UPDATED_STARTED = "RECENTLY_UPDATED_STARTED";
export const RECENTLY_UPDATED_FINISHED = "RECENTLY_UPDATED_FINISHED";

export const CHANGE_VISIBILITY_SPRINT_TIMELINE = 'CHANGE_VISIBILITY_SPRINT_TIMELINE';
export const CHANGE_VISIBILITY_TASK_STATUS = 'CHANGE_VISIBILITY_TASK_STATUS';
export const CHANGE_VISIBILITY_ISSUES = 'CHANGE_VISIBILITY_ISSUES';
export const CHANGE_VISIBILITY_BURNDOWN = 'CHANGE_VISIBILITY_BURNDOWN';

export const GET_PREFERENCES = "GET_PREFERENCES";
export const GET_SPRINT_ISSUES = "GET_SPRINT_ISSUES";

export const RELOAD_ISSUES = "RELOAD_ISSUES";
export const REFRESH_ISSUES = "REFRESH_ISSUES";
export const REFRESH_GANTT = "REFRESH_GANTT";
export const REFRESH_GANTT_STARTED = "REFRESH_GANTT_STARTED";
export const REFRESH_GANTT_FINISHED = "REFRESH_GANTT_FINISHED";

export const SEARCH_TEXT_CHANGED = "SEARCH_TEXT_CHANGED";
export const SET_COLLAPSING_SUBTASKS = "SET_COLLAPSING_SUBTASKS";
export const SET_COLLAPSING_BUGS = "SET_COLLAPSING_BUGS";
export const FILTER_STARRED_ISSUES = "FILTER_STARRED_ISSUES";

export const ADD_TASK_STATUS_FILTERS = "ADD_TASK_STATUS_FILTERS";
export const REMOVE_TASK_STATUS_FILTERS = "REMOVE_TASK_STATUS_FILTERS";

export const SET_SPRINT_SUMMARY = "SET_SPRINT_SUMMARY";
export const SET_SPRINT_DATES = "SET_SPRINT_DATES";
export const SET_SPRINT_ISSUES = "SET_SPRINT_ISSUES";
export const SET_SPRINT_VELOCITY = "SET_SPRINT_VELOCITY";

export const SET_ISSUES_SUMMARIES = "SET_ISSUES_SUMMARIES";
